In [20]:
class Patient:

    def __init__(self,a,name):
        #"Patient's age"
        self.age =a 
        self.name = name

    def yearh(self):
        #"The year when the patient will be 100"
        year =2124-self.age
        return year
P1= Patient(30,'Svidrigailov')
P1.yearh()

    

2094

In [3]:
import random
cpt1=0
cpt2=0

y=12
x=random.randint(0,9)
while(y!="exit")and(x!=y):
   
    print('please guess a number from 0 to 9')
    y=int(input())
    r=y-x
    if r==0:
        print(' Congratulations! You win ')
    elif r<0:
        print(' You guessed too low ')
        cpt1+=1
    else:
        print(' You guessed too high ')
        cpt2+=1
print(f"you tried {cpt1+cpt2+1} times")


please guess a number from 0 to 9


 5


 You guessed too high 
please guess a number from 0 to 9


 3


 You guessed too high 
please guess a number from 0 to 9


 2


 You guessed too high 
please guess a number from 0 to 9


 1


 You guessed too high 
please guess a number from 0 to 9


 0


 Congratulations! You win 
you tried 5 times


In [49]:
#Generating paswords
import random as rd
import string as st
list1=['damage','breakdown','chrono','eraserhead']
x=input('How strong do you want your password : type (weak) or (strong)')
pwd=""
listt=st.ascii_letters
if x=='weak':
   print(rd.choice(list1))
elif x=='strong':
   l=rd.randint(8,15)
   print(l)
   for i in range(l):
        theset=(str(rd.randint(0,9)),rd.choice(listt),rd.choice(st.punctuation))
        r=rd.choice(theset)
        pwd+=r
else:
        print('Are you blind? we said (weak) or (strong)!!')
print (f"We suggest this password:{pwd} ")              

How strong do you want your password : type (weak) or (strong) dueor


Are you blind? we said (weak) or (strong)!!
We suggest this password: 


In [196]:
f = open("Temp.txt", "r")
tempmax=[]
tempmin=[]
preci=[]
#data=[line.split(',') for line in f]
for line in data:
    
    if(len(line)>2):
        b=line[1]
        c=line[2]
        d=line[3]
        tempmax.append(int(b))
        tempmin.append(int(c))
        preci.append(float(d))
print(sum(tempmax)/10)
print(sum(tempmin)/10)
print(sum(preci))
 
       

15.2
5.1
9.8


In [236]:
import numpy as np
def initialisation(m,n):
    arr = np.random.randint(0,9,[m, n])
    arr1=np.ones((m,1))
    x=np.concatenate((arr,arr1),axis=1)
    return x
    
print(initialisation(13,14))


    

[[3. 2. 7. 7. 7. 7. 2. 7. 1. 0. 2. 2. 5. 8. 1.]
 [2. 8. 8. 1. 0. 0. 6. 8. 0. 8. 0. 6. 2. 1. 1.]
 [6. 0. 3. 3. 7. 7. 8. 8. 0. 1. 3. 8. 5. 0. 1.]
 [5. 3. 6. 3. 7. 6. 7. 3. 3. 1. 3. 2. 1. 7. 1.]
 [1. 6. 2. 4. 5. 3. 2. 2. 1. 5. 0. 6. 1. 3. 1.]
 [1. 3. 4. 3. 0. 3. 7. 6. 1. 5. 3. 6. 5. 2. 1.]
 [1. 8. 3. 4. 8. 8. 1. 2. 3. 6. 8. 0. 5. 2. 1.]
 [1. 4. 1. 4. 2. 7. 0. 7. 3. 7. 2. 0. 2. 5. 1.]
 [3. 6. 0. 0. 1. 5. 3. 4. 5. 5. 0. 3. 0. 6. 1.]
 [4. 8. 7. 6. 7. 7. 3. 2. 1. 5. 4. 3. 1. 3. 1.]
 [0. 8. 8. 6. 3. 3. 1. 5. 1. 4. 5. 4. 0. 5. 1.]
 [8. 8. 2. 8. 7. 6. 3. 5. 2. 0. 7. 4. 3. 8. 1.]
 [0. 3. 7. 5. 5. 4. 5. 5. 5. 6. 4. 6. 1. 2. 1.]]


In [246]:
B=np.zeros((4,4))
B[1:3,1:3]=1
print(B)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [260]:
C=np.zeros((6,6))
C[::2,::2]=1
print(C)

[[1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
# ### 7. **Stop gninnipS My sdroW!**
# Write a function that reverses every word in a string that is five or more characters long.
def revst(lst):
    for x in lst:
        if len(x)>=5:
            for j in range(len(x)//2):
                y=x[j]
                x[j]=x[len(x)-j-1]
                x[len(x)-j-1]=y
    return lst
revst(['ert','zerty','azerty'])
                
                

TypeError: 'str' object does not support item assignment